# Generated by Django 2.2.10 on 2020-02-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_orderitem_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default='CategoryOne', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='disc_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(default='LabelOne', max_length=30),
            preserve_default=False,
        ),
    ]
