# Generated by Django 2.1.1 on 2020-03-28 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_auto_20200328_1449'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BillingAddress',
            new_name='BillingAdd',
        ),
        migrations.AddField(
            model_name='order',
            name='billing_add',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.BillingAdd'),
        ),
    ]
